config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#home"

  # This was creted by the command: rails g scaffold...

  # resources :expenses
  # resources :group_expenses
  # resources :groups

  # This is the same as the below code, but with a personalized path:

  #resources :groups, only: [:index, :new, :create, :edit, :update, :destroy], :path => "categories" do 
  #  resources :expenses, only: [:index, :new, :create, :edit, :update, :destroy], :path => "transactions"
  #end

  resources :users, only: [ :home ]

  resources :groups, only: %i[index new create edit update destroy] do
    resources :expenses, only: %i[index new create edit update destroy]
  end

end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_expenses, dependent: :destroy
  has_many :expenses, through: :group_expenses, dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 },
                   format: { with: /\A[\w\s.-]+\z/,
                             message: 'solo se permiten letras, números, espacios en blanco, guiones y puntos' }

  validates :name, uniqueness: { scope: :author, message: 'You already have a category with this name' }

  validates :icon, presence: true, length: { maximum: 500 },
                   format: { with: %r{\Ahttps://.+\z}, message: 'Debe ser una URL con el protocolo HTTPS' }

  def total_expenses
    expenses.sum(:amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[edit update destroy]
  before_action :set_user, only: %i[index new edit create update destroy]

  # GET /groups or /groups.json
  def index
    @groups = @author.groups
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(author: @author, **group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Your New Categorie was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to groups_url, notice: 'Categorie was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'This Categorie was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @author = current_user
  end

  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:author_id, :name, :icon, :image)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, class:'form-container') do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h3><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h3>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, class: "text-field" %>
  </div>

  <div>
    <%= form.label :icon, class: "label" %>
    <%= form.text_area :icon, class: "text-field" %>
  </div>

  <div>
    <%= form.submit "#{action_name == 'edit' ? 'Update' : 'Save'}", class: "submit-button" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="group">
  <div>
    <%= link_to group_expenses_path(group) do%><img src="<%= group.icon %>" class="group-icon" alt="Group-Icon"><%end%>
  </div>

  <div class="group-name">
    <%= link_to group_expenses_path(group) do%><%= group.name %><%end%>
    <span class='small'><%= group.created_at.to_date %></span>
  </div>

  <p class="group-total-expenses">
    <%= number_to_currency(group.total_expenses) %>
  </p>

  <% if action_name != "show" %>
    <div class="group-actions">
    <%= link_to edit_group_path(group), class: "edit-actions" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="">
        <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
      </svg>
    <% end %>
    <%= button_to group_path(group), method: :delete, class: "delete-actions" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="">
       <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5m6 4.125l2.25 2.25m0 0l2.25 2.25M12 13.875l2.25-2.25M12 13.875l-2.25 2.25M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
      </svg>
    <% end %>
    </div>
  <% end %>

</div>

app/views/groups/edit.html.erb
<h2 class="edit-group-title">Edit your <span class="bold"><%= "#{@group.name}" %></span> Group</h2>

<%= render "form", group: @group %>

app/views/groups/index.html.erb
<div class="groups">
  <% @groups.each do |group| %>
    <%= render group %>
  <% end %>
</div>

<p class="notice" style="color: green"><%= notice %></p>
<div class="div-button">
  <%= link_to "New group", new_group_path, class: 'new-group' %>
</div>

app/views/groups/new.html.erb
<h2 class="edit-group-title">New group</h2>

<%= render "form", group: @group %>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>