config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#home"

  # This was creted by the command: rails g scaffold...

  # resources :expenses
  # resources :group_expenses
  # resources :groups

  # This is the same as the below code, but with a personalized path:

  #resources :groups, only: [:index, :new, :create, :edit, :update, :destroy], :path => "categories" do 
  #  resources :expenses, only: [:index, :new, :create, :edit, :update, :destroy], :path => "transactions"
  #end

  resources :users, only: [ :home ]

  resources :groups, only: %i[index new create edit update destroy] do
    resources :expenses, only: %i[index new create edit update destroy]
  end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[edit update destroy]
  before_action :set_group, only: %i[index new edit create update destroy]
  before_action :set_user, only: %i[index edit create update destroy]

  # GET /expenses or /expenses.json
  def index
    @expenses = @group.expenses.order(created_at: :desc)
  end

  # GET /expenses/1 or /expenses/1.json
  def show; end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @expenses = @group.expenses.order(created_at: :desc)
  end

  # GET /expenses/1/edit
  # def edit; end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(author: @author, **expense_params)

    respond_to do |format|
      if @expense.save
        format.html do
          @group_expense = GroupExpense.create(group: @group, expense: @expense)
          redirect_to group_expenses_url(@group), notice: 'Expense was successfully created.'
        end
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    if @expense.update(expense_params)
      redirect_to group_expenses_url, notice: 'Expense was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to group_expenses_url, notice: 'Expense was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @author = current_user
  end

  def set_group
    @group = set_user.groups.find(params[:group_id])
  end

  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:author_id, :name, :amount)
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense.html.erb
<div class="group">
  <p class="group-name">
    <%= expense.name %>
    <span class='small'><%= expense.author.name %></span>
    <span class='small'><%= expense.created_at.to_date %></span>
  </p>
  <p class="group-total-expenses">
    <%= number_to_currency(expense.amount) %>
  </p>

  <% if action_name != "show" %>
    <div class="group-actions">
    <%= link_to  edit_group_expense_path(@group, expense), class: "edit-actions" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="">
        <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
      </svg>
    <% end %>
    <%= button_to group_expense_path(@group, expense), method: :delete, class: "delete-actions" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="">
       <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5m6 4.125l2.25 2.25m0 0l2.25 2.25M12 13.875l2.25-2.25M12 13.875l-2.25 2.25M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
      </svg>
    <% end %>
    </div>
  <% end %>
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, url: "#{action_name == 'edit' ? group_expense_path(@group, expense) : group_expenses_path(@group)}", class: "form-container") do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, sclass: "label" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, class: "label" %>
    <%= form.text_field :amount, class: "text-field" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  
  <% @expenses.each do |cat| %>
    <div>
      <%= form.check_box :expense,{ multiple: true }, cat.id, nil %>
      <%= form.label cat.name %>
    </div>
  <% end %>
<% end %>

app/views/expenses/_formtwo.html.erb
<%= form_with(model: expense, url: "#{action_name == 'edit' ? group_expense_path(@group, expense) : group_expenses_path(@group)}", class: "form-container") do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, sclass: "label" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, class: "label" %>
    <%= form.text_field :amount, class: "text-field" %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/expenses/edit.html.erb
<h2 class="edit-group-title">Editing <span class="bold"><%= "#{@expense.name}" %></span> expense</h2>

<%= render "formtwo", expense: @expense %>

app/views/expenses/index.html.erb
<p class="notice"><%= notice %></p>

<div class="groups">
  <% @expenses.each do |expense| %>
    <%= render expense %>
  <% end %>
</div>

<div class="div-button">
  <%= link_to "New expense", new_group_expense_path, class: 'new-group' %>
</div>

app/views/expenses/new.html.erb
<h2 class="edit-group-title">New expense</h2>

<%= render "form", expense: @expense %>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %>

  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>